In [5]:
# 使用字典创建
import pandas as pd

data = {
    'Column1': [11, 22, 33],
    'Column2': ['A', 'B', 'C']
}
df = pd.DataFrame(data)
# print(df)
# # 
df

   Column1 Column2
0       11       A
1       22       B
2       33       C

In [6]:
# 访问列
column_data = df["Column1"]
column_data

0    11
1    22
2    33
Name: Column1, dtype: int64

In [7]:
# 访问行
row_data = df.loc[0] # 通过标签访问
row_data

Column1    11
Column2     A
Name: 0, dtype: object

In [8]:
# 访问行
row_data = df.iloc[0] # 通过 整数 位置访问
row_data

Column1    11
Column2     A
Name: 0, dtype: object

In [9]:
# 同时访问 行和列
df.loc[0:2,'Column1':'Column2']  # 选择 <0-2> 行 与 <'Column1'-'Column2'> 列 交会的区域

   Column1 Column2
0       11       A
1       22       B
2       33       C